<?php

declare(strict_types=1);

namespace DomainManager\Infrastructure\Platform\Windows;

use DomainManager\Domain\Project;
use DomainManager\Infrastructure\Platform\Contracts\ApacheManager;
use RuntimeException;

final readonly class WindowsApacheManager implements ApacheManager
{
    /** @param array<string, string> $phpRuntimes */
    public function __construct(
        private array $phpRuntimes,
        private string $certificateDirectory,
    ) {}

    public function renderVirtualHost(Project $project): string
    {
        $phpCgi = $this->phpRuntimes[$project->phpVersion] ?? null;

        if ($phpCgi === null || !is_file($phpCgi)) {
            throw new RuntimeException(sprintf('Nie znaleziono php-cgi.exe dla PHP %s.', $project->phpVersion));
        }

        $serverName = $project->primaryDomain()->value;
        $aliases = array_values(array_filter(
            array_map(static fn ($domain): string => $domain->value, $project->domains),
            static fn (string $domain): bool => $domain !== $serverName,
        ));
        $root = $this->apachePath($project->rootPath);
        $phpCgi = $this->apachePath($phpCgi);
        $phpDirectory = $this->apachePath(dirname($phpCgi));
        $common = $this->commonDirectives($root, $phpCgi, $phpDirectory);
        $serverAliases = $aliases === [] ? '' : "    ServerAlias " . implode(' ', $aliases) . "\n";

        $configuration = "# Generated by Domain Manager. Do not edit manually.\n";
        $configuration .= "<VirtualHost *:80>\n";
        $configuration .= "    ServerName {$serverName}\n{$serverAliases}{$common}</VirtualHost>\n";

        if ($project->httpsEnabled) {
            $certificateBase = rtrim($this->apachePath($this->certificateDirectory), '/') . '/' . $project->id;
            $configuration .= "\n<VirtualHost *:443>\n";
            $configuration .= "    ServerName {$serverName}\n{$serverAliases}";
            $configuration .= "    SSLEngine on\n";
            $configuration .= "    SSLCertificateFile \"{$certificateBase}/certificate.pem\"\n";
            $configuration .= "    SSLCertificateKeyFile \"{$certificateBase}/private-key.pem\"\n";
            $configuration .= $common . "</VirtualHost>\n";
        }

        return $configuration;
    }

    private function commonDirectives(string $root, string $phpCgi, string $phpDirectory): string
    {
        return <<<APACHE
    DocumentRoot "{$root}"

    <Directory "{$root}">
        Options FollowSymLinks ExecCGI
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html
    </Directory>

    FcgidInitialEnv PHPRC "{$phpDirectory}"
    <FilesMatch "\\.php$">
        SetHandler fcgid-script
    </FilesMatch>
    FcgidWrapper "{$phpCgi}" .php

APACHE;
    }

    private function apachePath(string $path): string
    {
        return str_replace('\\', '/', $path);
    }
}
